source 'https://github.com/CocoaPods/Specs.git'

target 'MobCat', :exclusive => true do
  pod "MobCat", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MobCat", :path => "../"

  
end
